apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common applications
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: common
    repoURL: https://github.com/NicCOConnor/argo-nco-k8s-home.git
    targetRevision: HEAD